# Generated by Django 5.2 on 2025-04-09 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('date', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Page2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('occupation', models.CharField(max_length=255)),
                ('citizenship_number', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('municipality_or_vdc', models.CharField(max_length=255)),
                ('date_of_birth', models.CharField(max_length=255)),
                ('fathers_name', models.CharField(max_length=255)),
                ('training_place', models.CharField(max_length=255)),
                ('training_date', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Page3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Page4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('date_of_birth', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('fathers_name', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('occupation', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('pan_number', models.CharField(max_length=255)),
                ('bank_name', models.CharField(max_length=255)),
                ('bank_account_number', models.CharField(max_length=255)),
                ('signed_date', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
