# Generated by Django 5.2 on 2025-04-10 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocrapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page1',
            options={'verbose_name': 'पृष्ठ 1', 'verbose_name_plural': 'पृष्ठ 1'},
        ),
        migrations.AlterModelOptions(
            name='page2',
            options={'verbose_name': 'पृष्ठ 2', 'verbose_name_plural': 'पृष्ठ 2'},
        ),
        migrations.AlterModelOptions(
            name='page3',
            options={'verbose_name': 'पृष्ठ 3', 'verbose_name_plural': 'पृष्ठ 3'},
        ),
        migrations.AlterModelOptions(
            name='page4',
            options={'verbose_name': 'पृष्ठ 4', 'verbose_name_plural': 'पृष्ठ 4'},
        ),
        migrations.AddField(
            model_name='page1',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='page2',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='page3',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='page4',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='page1',
            name='address',
            field=models.TextField(verbose_name='ठेगाना'),
        ),
        migrations.AlterField(
            model_name='page1',
            name='date',
            field=models.CharField(max_length=100, verbose_name='मिति'),
        ),
        migrations.AlterField(
            model_name='page1',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='नाम थर'),
        ),
        migrations.AlterField(
            model_name='page2',
            name='citizenship_number',
            field=models.CharField(max_length=50, verbose_name='नागरिकता नम्बर'),
        ),
        migrations.AlterField(
            model_name='page2',
            name='date_of_birth',
            field=models.CharField(max_length=100, verbose_name='जन्म मिति'),
        ),
        migrations.AlterField(
            model_name='page2',
            name='district',
            field=models.CharField(max_length=100, verbose_name='जिल्ला'),
        ),
        migrations.AlterField(
            model_name='page2',
            name='fathers_name',
            field=models.CharField(max_length=255, verbose_name='बुवाको नाम'),
        ),
        migrations.AlterField(
            model_name='page2',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='नाम थर'),
        ),
        migrations.AlterField(
            model_name='page2',
            name='gender',
            field=models.CharField(max_length=50, verbose_name='लिङ्ग'),
        ),
        migrations.AlterField(
            model_name='page2',
            name='municipality_or_vdc',
            field=models.CharField(max_length=100, verbose_name='नगरपालिका वा गा.वि.स.'),
        ),
        migrations.AlterField(
            model_name='page2',
            name='occupation',
            field=models.CharField(max_length=100, verbose_name='पेशा'),
        ),
        migrations.AlterField(
            model_name='page2',
            name='training_date',
            field=models.CharField(max_length=100, verbose_name='तालिम मिति'),
        ),
        migrations.AlterField(
            model_name='page2',
            name='training_place',
            field=models.CharField(max_length=255, verbose_name='तालिम लिएको स्थान'),
        ),
        migrations.AlterField(
            model_name='page3',
            name='address',
            field=models.TextField(verbose_name='ठेगाना'),
        ),
        migrations.AlterField(
            model_name='page3',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='नाम थर'),
        ),
        migrations.AlterField(
            model_name='page4',
            name='address',
            field=models.TextField(verbose_name='ठेगाना'),
        ),
        migrations.AlterField(
            model_name='page4',
            name='bank_account_number',
            field=models.CharField(max_length=50, verbose_name='बैंक खाता नम्बर'),
        ),
        migrations.AlterField(
            model_name='page4',
            name='bank_name',
            field=models.CharField(max_length=100, verbose_name='बैंकको नाम'),
        ),
        migrations.AlterField(
            model_name='page4',
            name='date_of_birth',
            field=models.CharField(max_length=100, verbose_name='जन्म मिति'),
        ),
        migrations.AlterField(
            model_name='page4',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='इमेल'),
        ),
        migrations.AlterField(
            model_name='page4',
            name='fathers_name',
            field=models.CharField(max_length=255, verbose_name='बुवाको नाम'),
        ),
        migrations.AlterField(
            model_name='page4',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='नाम थर'),
        ),
        migrations.AlterField(
            model_name='page4',
            name='gender',
            field=models.CharField(max_length=50, verbose_name='लिङ्ग'),
        ),
        migrations.AlterField(
            model_name='page4',
            name='mobile_number',
            field=models.CharField(max_length=20, verbose_name='मोबाइल नम्बर'),
        ),
        migrations.AlterField(
            model_name='page4',
            name='occupation',
            field=models.CharField(max_length=100, verbose_name='पेशा'),
        ),
        migrations.AlterField(
            model_name='page4',
            name='pan_number',
            field=models.CharField(max_length=50, verbose_name='प्यान नम्बर'),
        ),
        migrations.AlterField(
            model_name='page4',
            name='signed_date',
            field=models.CharField(max_length=100, verbose_name='साइन मिति'),
        ),
    ]
